### PR TITLE
Add ability to alter xml before sent

### PR DESCRIPTION
**Pull request by rafal83**
add to option "postProcess" to add ability to alter xml before sent

### CODE REVIEW

**Comment by jsdevel** [comment]
Please add a sample to the tests and update the readme

**Comment by herom** [comment]
@rafal83 thanks a lot for your contribution 👍 - I think what @jsdevel wanted to tell was to add tests & update the readme within this very PR, but I'm glad to merge in your PRs if you could please give them proper titles. These titles will help us when merging as well as when we're creating the `CHANGELOG.md` 😸 

Please rename your PRs and add a short description of their content (e.g. Tests, Update Documentation) and we're good to go 🚀 

@jsdevel are you ok if we take this merge order?:
1) Test (failing `node-soap` when merged)
2) Implementation (fixes failing test)
3) Documentation

**Comment by jsdevel** [comment]
> @jsdevel are you ok if we take this merge order?:

I'd prefer if the other PRs were merged into this one.  That way when we merge it's easier to track in History.md etc.

**Comment by herom** [comment]
>I'd prefer if the other PRs were merged into this one. That way when we merge it's easier to track in History.md etc.

Agreed - this would definitely make it a lot easier 💯

**Comment by herom** [comment]
thanks a ton @rafal83 👍

**Pull request merged**
