### PR TITLE
When an error occur, send HTTP 500 status code

### PR DESCRIPTION
**Pull request by greuze**
Now status 200 OK is returned, and is confusing.

### CODE REVIEW

**Comment by jsdevel** [comment]
Can you add a test for this?

**Comment by greuze** [comment]
Added unit test

**Comment by greuze** [comment]
Sending a wrong XML returns now HTTP 500. I used XML in the post request in order to work in all node.js versions.

**Comment by jsdevel** [comment]
Can you squash down to 2 commits?

**Comment by greuze** [comment]
They are already 2 commits, you mean to one commit?

**Comment by jsdevel** [comment]
> They are already 2 commits, you mean to one commit?

Yes.

**Comment by greuze** [comment]
Done :+1:

**Comment by jsdevel** [comment]
Thanks!

**Pull request merged**
