### PR TITLE
SOAP 1.2 Headers and HTTP Content-Type - Q&D Fix

### PR DESCRIPTION
**Pull request by neversaid**
Even if its a Quick and Dirty fix, it helps to work with my SOAP12 Service flawless.
Theres a new function setSOAPVersion12 for the client (true | false) implemented to set the SOAP12 Headers and Content-Type. As well it can be determined by getSOAPVersion12 to see if Soap12 is enabled.

### CODE REVIEW

**Comment by jmaslin** [comment]
Thank you, this works perfectly!

**Comment by herom** [comment]
Hello @neversaid - thanks a lot for your contribution and sorry for the extremely long delay :disappointed: 

In order to get your PR merged I'll have to ask you to follow our [Guideline on Submitting a Pull Request](https://github.com/vpulim/node-soap/blob/master/CONTRIBUTING.md#submitting-a-pull-request) and work through the open points, which are:

- Add accompanying tests
- Rebase/Squash your commits into a single one (more information about this topic is given in the guideline)
- Run `npm test` locally and take a look at the Travis CI logs in order to make the PR pass all the tests

Thanks a lot for your patience :+1:

**Comment by alhafoudh** [comment]
I am sorry, but how can I use this? I got the custom repository in my package.json, but how can I invoke the setSOAPVersion12 ?

**Comment by herom** [comment]
If you've created a client, you should be able to call `client.setSOAPVersion12(true);` :+1:

**Comment by leichenau** [comment]
Has this been released? It will be really nice to have it.

**Comment by jsdevel** [comment]
Closing for lack of activity.

**Comment by fleg** [comment]
request-response test would be enough?

**Comment by herom** [comment]
We'd need a proper PR which respects our [Guidelines on Submitting a Pull Request](https://github.com/vpulim/node-soap/blob/master/CONTRIBUTING.md#submitting-a-pull-request) stated in our [CONTRIBUTING.md](https://github.com/vpulim/node-soap/blob/master/CONTRIBUTING.md) file :+1:

**Comment by somethingnothingforsomething** [comment]
We have problem in setting the credential to the service call in node soap.
soap.createClient(url, {
        wsdl_options: {
            proxy: '---------',
            timeout: 5000,
            connection: 'keep-alive',
            pfx: publicKey,
            strictSSL: true,
            passphrase: password

        }
    }, function (err, client) {
        if (err)
        {
            console.log(err)
        } else
        {

         }

//we are able to get the client object, so the connection is estableshed now. But when we are trying to call the soap service method from the client object , like client.soapname.port.function. We are not able to call it. Simply the soap methods are not calling. Is it required to pass the certificate credential again in service method call ? If so, then how can we  pass certificate in function call ?

The call is as follows : 
client.Servicename.port.methodName({}, function (err, res) {
                if (err) {
                } else {
                }
            });
We are not able to call the method

**Pull request closed without merging**
