### PR TITLE
fix parameter being passed in

### PR DESCRIPTION
**Pull request by kguirguis**

### CODE REVIEW

**Comment by herom** [comment]
thanks a lot for your contribution @kguirguis 👍 

as I see there was a second commit with a "rollback"... can we close this request?

**Comment by kguirguis** [comment]
For example, I run the function: RetrieveServiceContent

And the xml ends up being:

<?xml version="1.0" encoding="UTF-8"?>
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:interface="urn:vim25" xmlns:reflect="urn:reflect" xmlns:vim25="urn:vim25" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
   <soap:Body>
      <RetrieveServiceContentRequestMsg>
         <_this>ServiceInstance</_this>
      </RetrieveServiceContentRequestMsg>
   </soap:Body>
</soap:Envelope>

**Comment by herom** [comment]
You can see the failing tests in detail over at Travis CI - so, if you mind to "rollback the rollback" 😁 you can take a look at the failing test results there 👍

**Comment by kguirguis** [comment]
Sounds good! Haha :)

**Pull request closed without merging**
