### PR TITLE
Added override constructor to ClientSSLSecurityPFX class

### PR DESCRIPTION
**Pull request by willemruys**
The declaration of [constructor overloads](https://www.typescriptlang.org/docs/handbook/2/classes.html#constructors) for ClientSSLSecurityPFX was missing one constructor definition. As a consequence, `ClientSSLSecurityPFX.d.ts` defined only one constructor:
```
../ClientSSLSecurityPFX.d.ts

export declare class ClientSSLSecurityPFX implements ISecurity {
    private pfx;
    private defaults;
    private passphrase;
    constructor(pfx: string | Buffer, defaults?: any);
    toXML(): string;
    addOptions(options: any): void;
}
```
I've added the constructor definition and the definition file showed both constructor methods.

### CODE REVIEW

**Comment by willemruys** [comment]
@jsdevel I've added a test and squashed my commits into 1 commit. Please let me know if I can do anything else.

**Comment by jsdevel** [comment]
@willemruys can you fix the build?

**Comment by willemruys** [comment]
@jsdevel Done! I fixed the failing test

**Comment by willemruys** [comment]
@jsdevel sorry for the trouble. Some tests in the WSDLParser seem to be failing. Not sure what caused it. I’ll have a look tomorrow or Monday and push a fix.

**Comment by willemruys** [comment]
Unfortunately, the failing tests seem to be unrelated to my changes and what I can see from other PRs, they are occurring there as well. I'll try to do my best to fix them.

**Comment by jsdevel** [comment]
i'm willing to accept that the test may have to be removed.  i think the failing test is trying to fetch XSD files that are now 404.

**Comment by willemruys** [comment]
@jsdevel I've disabled the test using the PurchaseRequestService.wsdl and deleted the PurchaseRequestService files since they indeed contained links that returned 404.

**Comment by tommyhtran** [comment]
@jsdevel Is there anything holding up this PR?

**Pull request merged**
