### PR TITLE
Twice soap action qoute

### PR DESCRIPTION
**Pull request by sm2017**
I have issue with soap client, it send bad requests
I inspect network and see that SOAPAction header qouted twice

```
SOAPAction: "\"SOAPAction\""

```

I know that my PR is not good fix, As there is no issue option I make a PR
Sorry for that

### CODE REVIEW

**Comment by sm2017** [comment]
@vpulim can you help me?

**Comment by jsdevel** [comment]
@sm2017 please add a test

**Comment by sm2017** [comment]
@jsdevel can you show me why SOAPAction
qouted twice?

**Comment by jsdevel** [comment]
@sm2017 nope.  i don't understand the code.  i just ensure that contributors follow the process, and i publish changes.

**Pull request closed without merging**
