### PR TITLE
handle base attribute on WSDL.prototype.findChildSchemaObject

### PR DESCRIPTION
**Pull request by KnutEdelbert**
When parsing the wsdl, the trace don't recognize the reference in the base attribute of an ExtensionElement, when it comes to findChildSchemaObject. It should be handled like the type attribute on ElementElements, but don't know what it's about with the "backtrace.length === 1".

It's my first pull request - I think, this minor changes don't need an extra test - but please let me know, if something is missing. 

Additionally i don't know how to handle the diffs in package-lock.json....

### CODE REVIEW

**Comment by KnutEdelbert** [comment]
Ok, that's confusing. After fixing the lint error, all errors in the CI log have nothing to do with my changes. So i don't know, why the coverage is decreasing or why the checks fail at all.
Can anybody tell me, what's wrong? Thank you in advance!

**Comment by jsdevel** [comment]
@KnutEdelbert please add a test

**Comment by KnutEdelbert** [comment]
@jsdevel i added a test, but the travis CI build failed on other tests and aborted the tests. My test was not executed. What to do now? @vpulim can you help?

**Comment by jsdevel** [comment]
will merge once the build passes.  can you bump coverage more of the code you added?

**Comment by KnutEdelbert** [comment]
Sorry, i'm fairly new to all this processes, i don't know exactly what you mean.

I've added a test for the added code (and it covers this code), but according to the CI build log, this test is never executed because of (too?) many failing tests before mine.

For me it seems, that the code base i've forked never passes the tests either. So i really don't know what to do, to get the CI Build executing my tests. It's kind of frustrating, but maybe it's because of my inexperience.

Can you help my with my struggle? What has to be done to get my test executed?

**Comment by jsdevel** [comment]
@KnutEdelbert then it's possible this change broke other tests.  can you look at that?

**Comment by KnutEdelbert** [comment]
That's a good point - i'll take a look at it. Thank you!

**Comment by KnutEdelbert** [comment]
Ok, npm run lint won't work for me on 0.35. Locally it worked with 0.36. So i close this request an open a new one from 0.36 and hope, that everything will work there.

**Pull request closed without merging**
