### PR TITLE
add handling for extension base without children

### PR DESCRIPTION
**Pull request by KnutEdelbert**
When parsing the wsdl, the trace don't recognize the reference in the base attribute of an ExtensionElement without child nodes, when it comes to findChildSchemaObject. It should be handled like the type attribute on ElementElements

### CODE REVIEW

**Comment by KnutEdelbert** [comment]
ok, finally, it looks good.
@jsdevel: is there anything else i have to do now?

**Comment by jsdevel** [comment]
@KnutEdelbert please remove the change to package-lock.json

**Comment by KnutEdelbert** [comment]
@jsdevel  as you wish - it's deleted

**Comment by KnutEdelbert** [comment]
ok, i think it was better to revert the file instead of deleting it....
@jsdevel Everything ok now?

**Pull request merged**
