### PR TITLE
xsi:type currently requires a namespace, resulting in undefined if no…

### PR DESCRIPTION
**Pull request by newmaniese**
… XMLNS is defined. Making attributes working without namespace or xmlns definitions.

### CODE REVIEW

**Comment by newmaniese** [comment]
Updated, should be passing now. 

Sorry that it didn't pass the first time, Oracle's servers were down for the remote XSD, and I didn't realize it bailed on the first failure.

**Comment by jsdevel** [comment]
@newmaniese build is still failing.  can you take a look?

**Comment by newmaniese** [comment]
Looking, thanks

**Comment by newmaniese** [comment]
Managed to not push my changes. Please run it again and thank you.

**Comment by newmaniese** [comment]
Looking again

**Comment by jsdevel** [comment]
@newmaniese the build is still failing.  please run these on your local machine.

**Comment by newmaniese** [comment]
Tests were/are passing and missed a lint command. Fixed all good. Thanks

**Comment by newmaniese** [comment]
Thanks, sorry for the back and forth!

**Pull request merged**
