### PR TITLE
SOAP Headers for server response

### PR DESCRIPTION
**Pull request by mdhooge**
I copied the client methods that handle SOAP headers to be able to also put headers in server replies.
I also created a method to be able to change an existing header (without having to purge all others and recreate everything).

And I re-organized a bit the readme.

### CODE REVIEW

**Comment by mdhooge** [comment]
@herom: while I'm doing rebase (#797) do you want me to also rebase that one? ;-)

**Comment by herom** [comment]
sorry for the late response @mdhooge - this would be awesome :dancer:

**Comment by mdhooge** [comment]
Should be ok…

**Comment by herom** [comment]
Great! :+1:

**Pull request merged**
