### PR TITLE
Include correct namespace alias for operations without parameters

### PR DESCRIPTION
**Pull request by tdecaluwe**
Add the correct namespace alias for operations without parameters by simply removing the special case where input.parts is empty. If special logic is wanted for this case, it should be contained in objectToRpcXML in any case.

### CODE REVIEW

**Comment by tdecaluwe** [comment]
Since `typeof(null)` will never be `'string'` this commit does not change the behaviour of the conditional.

**Comment by jsdevel** [comment]
THis PR needs tests.

**Comment by tdecaluwe** [comment]
I added a request sample to test operations without params.

**Comment by jsdevel** [comment]
Thanks!

**Pull request merged**
