### PR TITLE
Fix fault throwing

### LINKED ISSUE #744: Fault error message undefined
Upgrading from `0.9.1` to `0.9.4`, errors thrown for SOAP faults don't show the error message anymore:

**Fault Response**
```xml
<?xml version="1.0" encoding="UTF-8"?>
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:sf="urn:fault.partner.soap.sforce.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <soapenv:Body>
        <soapenv:Fault>
            <faultcode>sf:MALFORMED_QUERY</faultcode>
            <faultstring>MALFORMED_QUERY: SOQL statements cannot be empty or null</faultstring>
            <detail>
                <sf:MalformedQueryFault xsi:type="sf:MalformedQueryFault">
                    <sf:exceptionCode>MALFORMED_QUERY</sf:exceptionCode>
                    <sf:exceptionMessage>SOQL statements cannot be empty or null</sf:exceptionMessage>
                    <sf:row>-1</sf:row>
                    <sf:column>-1</sf:column>
                </sf:MalformedQueryFault>
            </detail>
        </soapenv:Fault>
    </soapenv:Body>
</soapenv:Envelope>
```

**Expected**
```
Error: sf:MALFORMED_QUERY: MALFORMED_QUERY: SOQL statements cannot be empty or null: [object Object]
```

**Actual**
```
Error: undefined: undefined
```

### PR DESCRIPTION
**Pull request by SEAPUNK**
This fixes #744

SOAP response is in #744 - I am experiencing the same issue with a different SOAP API (stamps.com SOAP API)

### CODE REVIEW

**Comment by herom** [comment]
Thanks a lot for your contribution @SEAPUNK - we appreciate it a lot :+1: 

Please, in order to get your PR merged, follow our [Guidelines on Submitting a Pull Request](https://github.com/vpulim/node-soap/blob/master/CONTRIBUTING.md#submitting-a-pull-request) (see also the tags of this PR).

**Comment by SEAPUNK** [comment]
Agh, I'm having one hell of a time rebasing; this might take a bit.

**Comment by SEAPUNK** [comment]
There we go; does this work?

**Comment by jsdevel** [comment]
the rebase looks good.  We need some request/response samples though in order to merge.

**Comment by SEAPUNK** [comment]
I cannot provide a request (as it includes sensitive data), but I do have a response (as well as a response shown in #744), although I need some time to dig that up as well.

**Comment by jsdevel** [comment]
you can rename endpoints etc. so it isn't sensitive.

**Comment by SEAPUNK** [comment]
Request (stipped of sensitive data):

```
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:tm="http://microsoft.com/wsdl/mime/textMatching/" xmlns:tns="http://stamps.com/xml/namespace/2015/01/swsim/swsimv42" xmlns:s1="http://microsoft.com/wsdl/types/">
    <soap:Body>
        <GetRates xmlns="http://stamps.com/xml/namespace/2015/01/swsim/swsimv42">
            <Credentials>
                <IntegrationID>xxxxxxxxxxxxxxxxxxxxxxxx</IntegrationID>
                <Username>xxxxxxxxxxxxxxxxxxxxxxx</Username>
                <Password>xxxxxxxxxxxxxxxxxxx</Password>
            </Credentials>
            <Rate>
                <FromZIPCode>xxxxx</FromZIPCode>
                <ToZIPCode>xxxxx</ToZIPCode>
                <ServiceType>xxxxx</ServiceType>
                <WeightLb>1000000.00</WeightLb>
                <PackageType>Package</PackageType>
                <Length>100000000000.00</Length>
                <Width>100000000000000.00</Width>
                <Height>1000000000000000.00</Height>
                <ShipDate>2015-10-20</ShipDate>
            </Rate>
        </GetRates>
    </soap:Body>
</soap:Envelope>
```


Response:

```
<?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <soap:Body>
        <soap:Fault>
            <faultcode>soap:Client</faultcode>
            <faultstring>Invalid SOAP message due to XML Schema validation failure. The 'http://stamps.com/xml/namespace/2015/01/swsim/swsimv42:Length' element is invalid - The value '100000000000.00' is invalid according to its datatype 'http://stamps.com/xml/namespace/2015/01/swsim/swsimv42:double-le-999' - The MaxInclusive constraint failed.</faultstring>
            <faultactor>http://swsim.stamps.com/swsim/swsimv42.asmx</faultactor>
            <detail>
                <stamps_exception code="00490102" xmlns="http://stamps.com/xml/namespace/2008/02/stamps/fault" />
            </detail>
        </soap:Fault>
    </soap:Body>
</soap:Envelope>
```

**Comment by jsdevel** [comment]
Please include it in the commit.

**Comment by SEAPUNK** [comment]
As a test in `test/client-test.js`?

**Comment by jsdevel** [comment]
`test/request-response-samples`.

**Comment by evantahler** [comment]
Great catch! I'm having the same errors even when generating a Fault with this library, ie:

```
Fault: {
          faultcode: "soap:Client.BadArguments",
          faultstring: String(message.error)
        }
```

=> Error: undefined: undefined

**Comment by jguepin** [comment]
:+1:

**Comment by SEAPUNK** [comment]
By the way, I don't think I'll be able to create the test, but anyone can feel free to continue where I left off.

**Comment by SEAPUNK** [comment]
Closed since #771 is merged

**Pull request closed without merging**
