### PR TITLE
Updated extend() for null and typeof checks PR 2

### PR DESCRIPTION
**Pull request by ramotswa**
2nd pull request to include test wsdl (sorry, didn't know how to update the PR rather than close and re-create it).

### CODE REVIEW

**Comment by herom** [comment]
@ramotswa Thanks for your PR although it would have been a better solution to ask first how to rebase/squash a commit before closing the other in favour for a new one. :smile_cat: 

So, according to our [Guidelines on Submitting a Pull Request](https://github.com/vpulim/node-soap/blob/master/CONTRIBUTING.md#submitting-a-pull-request) I'll have to ask you to squash/rebase your commits into a single one before I'm able to merge your contribution. Please see the links to the (excellent!) GitHub Help Pages in our guidelines on this topic. :+1:

**Comment by ramotswa** [comment]
Ok so I have rebased and squashed my branch.. how do I go about updating this PR?

**Comment by herom** [comment]
Thanks a lot! 
Your PR is updated automatically (just look at this PRs "Commits" Tab - it shows only 1 commit) :+1:

**Comment by ramotswa** [comment]
Ah yes. very nice. Hope the code is ok!

**Comment by herom** [comment]
Could you please do me a last favour? It would be awesome if you could edit the commit's message to the last one? This should be possible with either `git rebase -i HEAD~1` and updating the commit message (just prefix all other lines with `#`) or with a `git reset --soft HEAD~1` (please see that it says **--soft**, if you don't use a flag or do `--hard` all your code changes will be lost!) and a fresh commit with the edited text.

So, right now, your commit message reads 
```
Added test wsdl for testing purposes.

Updated extend() for null and typeof checks

The extend function was throwing an error (vpulim#585). This null and typeof check will handle elements that are not objects.
```

And it should look like
```
The extend function was throwing an error (#585). This null and typeof check will handle elements that are not objects.
```

This would be awesome :+1: - thanks in advance :smiley:

**Comment by ramotswa** [comment]
Hey @herom - I really hope this is ok and I haven't messed things up! Still learning!

**Comment by herom** [comment]
ahhhm... now there are 3 commits which obviously don't belong to yours.... hmmmmm.... seems like something went terribly wrong.... I see what I can do....

**Comment by herom** [comment]
Please rebase your project against `node-soap:vpulim/master` and (force) push it onto your project:

Follow these steps to rebase it against `node-soap:vpulim/master`:
- Add `node-soap:vpulim` as remote fork --> [GitHub Help:: Configuring a remote for a fork] (https://help.github.com/articles/configuring-a-remote-for-a-fork/)
- Rebase your 'master' branch with the following steps:
1) `git fetch upstream upstream`
2) `git rebase upstream/master`
- Force push onto your GitHub project

this should do the trick :+1: 

Please, in all situations, before you work on this, make a copy of your local project so that you have always backup.

**Comment by ramotswa** [comment]
Ooo, I think that might have done it. Well done - sorry for causing such pain for such a small edit!

**Comment by herom** [comment]
Thanks a lot for your time & effort @ramotswa - we appreciate every contribution to make `node-soap` better & more solid :smiley:

**Pull request merged**
