### PR TITLE
Fix exception 'Parameter 'url' must be a string, not object'

### PR DESCRIPTION
**Pull request by iuriibesedin**

### CODE REVIEW

**Comment by jsdevel** [comment]
can you add a test?

**Comment by iuriibesedin** [comment]
I've added the test.

**Comment by jsdevel** [comment]
Thanks!  Looks like there's a conflicting file.  Can you `git pull --rebase upstream master`?

**Comment by iuriibesedin** [comment]
Done, can you check?

**Comment by iuriibesedin** [comment]
When will you be able to merge this fix to master?

**Comment by jsdevel** [comment]
Thanks @iuriibesedin !

**Comment by iuriibesedin** [comment]
when are you going to release last fixes to npm?

**Pull request merged**
