### PR TITLE
Catch errors when parsing WSDL

### PR DESCRIPTION
**Pull request by ivank**
Hey guys great library. Just noticed this problem and am providing a small PR.

We've had bad WSDLs from a service we've been calling and the lib was dying without any way to catch the errors.

Because the process to parse the WSDL is placed in `nextTick` any exception that is thrown results in our service dying.

```
TypeError: Cannot read property 'elements' of undefined at MessageElement.postProcess (/home/node/app/node_modules/soap/lib/wsdl/elements.js:599:35) at OperationElement.postProcess (/home/node/app/node_modules/soap/lib/wsdl/elements.js:876:21) at PortTypeElement.postProcess (/home/node/app/node_modules/soap/lib/wsdl/elements.js:919:19) at BindingElement.postProcess (/home/node/app/node_modules/soap/lib/wsdl/elements.js:965:22) at ServiceElement.postProcess (/home/node/app/node_modules/soap/lib/wsdl/elements.js:1041:29) at /home/node/app/node_modules/soap/lib/wsdl/index.js:96:40 at WSDL._processNextInclude (/home/node/app/node_modules/soap/lib/wsdl/index.js:1057:20) at WSDL.processIncludes (/home/node/app/node_modules/soap/lib/wsdl/index.js:146:14) at /home/node/app/node_modules/soap/lib/wsdl/index.js:87:19 at process._tickCallback (internal/process/next_tick.js:61:11)
```

This change just wraps the code in a try catch block and calls the callback with the error.

I've tried to slim down the WSDL as much as I can but am not versed in it enough. If you guys think there is a smaller test WSDL we can use I'll be happy to change that.

And awesome library BTW!

### CODE REVIEW

**Comment by SWAG-DevTeam** [comment]
Hello, how can I Read MTOM attachements with node soap ?

**Comment by SWAG-DevTeam** [comment]
Hi ivank.

why are you confused ?
My question seems not understandable ?
Sorry for my english.

**Comment by ivank** [comment]
Hey @SWAG-DevTeam are you sure you're talking about the same ticket?

> Hi all, how can I Read MTOM attachements with node soap plz ?
> i am supposed to use : client.methode(arg, callback, options).
> Attachements are in the callback ?

This Pull Request is just adding a try catch around a function during initialisation of the client. No methods, services, attachments or anything else.

**Comment by SWAG-DevTeam** [comment]
Right, Sorry ;-)

**Pull request merged**
