### PR TITLE
Add XML declaration in client requests

### PR DESCRIPTION
**Pull request by mdhooge**

### CODE REVIEW

**Comment by jsdevel** [comment]
Change looks good.  Was this causing an issue with a service you were consuming?

**Comment by mdhooge** [comment]
Well, I'm just trying to comply with the requirements of OCPP 1.6-soap. Section 3.1 says this XML declaration _should_ be prepended. So… why not having it for every body? :)
http://www.openchargealliance.org/download

**Comment by herom** [comment]
Could you please rebase your PR @mdhooge - after that I'm glad to merge your PR :+1:

**Comment by mdhooge** [comment]
OK, 160 passing tests

**Comment by herom** [comment]
Thanks a ton @mdhooge :+1:

**Pull request merged**
