### PR TITLE
Fix including xsd from another xsd while using inline xmlns

### PR DESCRIPTION
**Pull request by e6c31d**

### CODE REVIEW

**Comment by jsdevel** [comment]
@e6c31d plz get the build to pass

**Comment by e6c31d** [comment]
@jsdevel I don't think the build failure is related to this PR. It builds successfully for me on Node.js 14 and 16, but not on 18. The build also fails on the master branch on Node.js 18.

**Comment by e6c31d** [comment]
@jsdevel I created another PR to fix the build on Node.js 18: #1206

**Comment by w666** [comment]
Hi @e6c31d,

I rebased you branch to check if it still works, I recently released new version with some major changes. 

I will merge it and include into next release.

**Review by w666 — APPROVED** [review]

**Pull request merged**
