### PR TITLE
updated axios and axios-ntlm to latest

### PR DESCRIPTION
**Pull request by vision10**
latest version of axios-ntlm fixes node v18 digital envelope error
Error: error:0308010C:digital envelope routines::unsupported

updated axios to latest: 1.3.2
updated axios-ntlm to latest: 1.4.0 (uses axios 1.3.2)

also 2 tests where failing because of hardcoded response Content-Length

this request needs to be accepted to pass all tests: https://github.com/vpulim/node-soap/pull/1206

### CODE REVIEW

**Comment by valdiss** [comment]
Same here, we're upgrading to node 18 and now need to --force to do any npm install...

**Comment by RezaRahmati** [comment]
Looking forward to get this changes

**Comment by T4kumi-js** [comment]
Looking forward to see this update too!

**Comment by jsdevel** [comment]
@vision10 plz fix the build

**Comment by vision10** [comment]
@jsdevel I have included changes from https://github.com/vpulim/node-soap/pull/1206
build should be ok

**Comment by lsaadeh** [comment]
@jsdevel are we happy to merge now?

**Comment by vision10** [comment]
is there no one able to merge here?
axios is already at 1.4.0 since this pull request
some of the other pull requests can be closed or just need a bit of attention

**Comment by T4kumi-js** [comment]
idk, this seems like a sleeping law in congress

**Comment by RezaRahmati** [comment]
We might need to sign a competition for this PR to get merged 😆

**Comment by SaundersB** [comment]
Agreed it would be great to see this merged

**Comment by guilhermeledes** [comment]
Bump. This is a critical update.

**Comment by codersbet** [comment]
Any update on this one @vpulim

**Comment by SaundersB** [comment]
FYI. In order to continue to use this package we all need to now use `--force` or `--legacy-peer-deps` until this is merged. Or we will need to find an alternative. Can we maybe delegate somebody to maintain this library since there are many of us who would contribute to resolve things like this?

**Comment by Unknown051** [comment]
+1

**Comment by zindont** [comment]
+1

**Comment by pedrokaroth** [comment]
+1

**Comment by DydjyZ** [comment]
sdfghujiopm

**Comment by random42** [comment]
Hi, why is axios a peer dependency any way? I can't see the reason. If we could move it as a normal dependency we wouldn't be here waiting for using axios 1.0 and this library together.

**Comment by antirek** [comment]
+1

**Comment by AdrianFahrbach** [comment]
Same here!
@vpulim Any chance to get this merged?

**Comment by nicolae536** [comment]
Any timeline for when this pr will be merged and released ? 🤔

**Comment by lukeTheWizard** [comment]
Merge please this is ruining the package

**Comment by vision10** [comment]
We seriously need someone to accept these pull requests that are piling up, not just mine
@vpulim please give someone access to manage this repository if you are too busy

axios version has known vulnerabilities
https://security.snyk.io/vuln/SNYK-JS-AXIOS-6032459

**Comment by alfaproject** [comment]
@RJWerning can you confirm that the override works? I didn't want to risk it because it's a major version upgrade but now there's this new security vulnerability...

**Comment by codersbet** [comment]
If I fork this repo and start maintaining it will someone also help out?

I am planning on forking it to a new repo and start maintaining it. Who is in?

**Comment by derodero24** [comment]
@codersbet Although I may not be able to actively participate in the maintenance, I'm very supportive of the idea if you're willing to take the lead in managing it.

**Comment by RishikeshDarandale** [comment]
@vpulim , Can you please merge this one?

@codersbet , @rmarfil3 created the fork, but not sure if he is publishing it to `npm`!

**Comment by kevinccbsg** [comment]
Hi @vpulim thanks a lot for this package. When do you think it will be ready the new release?

**Comment by savez** [comment]
Warning.

axios 1.6.1 has an error.

With soap@1.0.1 I have an error in my unit test with this message: 'Cannot use import statement outside a module'.

I have reverted back to version 1.0.0 and have no errors.

**Comment by w666** [comment]
Hi @savez, could please add some details, like your environment and logs? 
I've tested 1.0.1 release in my project and it worked just fine. We run it in node.js 20.

**Comment by w666** [comment]
> Hi @vpulim thanks a lot for this package. When do you think it will be ready the new release?

New version 1.0.1 has been released.

**Comment by savez** [comment]
> Hi @savez, could you please add some details, like your environment and logs? 
> I've tested 1.0.1 release in my project and it worked just fine. We run it in node.js 20.

Yes, 
I'm using node20.

But when I running jest it show an error.

**Comment by w666** [comment]
If you can post you jest config and tsconfig that would help to identify the problem.
In my tests I just mock soap requests so don't really use it. 
Unfortunately, I am very limited in time and can't setup test project to test it.

**Pull request merged**
