### PR TITLE
Reverting #914

### PR DESCRIPTION
**Pull request by jsdevel**
cc @herom @pihvi

### CODE REVIEW

**Comment by jsdevel** [comment]
Just a heads up @vfrbgt, #914 broke existing behavior, so we're going to be reverting it.  If you can re-apply your changes from #914 in a way that allows the latest tests from @pihvi to pass we'll happily merge them back.

**Comment by jsdevel** [comment]
Published as `v0.19.1` cc @herom

**Comment by anttimattila** [comment]
Works now, thanks for the fast response!

Also just want to say I was a bit terrified to have to work with SOAP in my project. I wanted to try if Node.js could handle soap. And when it was just npm install soap, read the wsdl and I got a working client with all the methods eating JSON, I was just blown away and happy! It's _almost_ better than REST ;) But anyway.. THANK YOU for node-soap!

**Comment by pihvi** [comment]
Works now, thanks for the fast response!

Also just want to say I was a bit terrified to have to work with SOAP in my project. I wanted to try if Node.js could handle soap. And when it was just npm install soap, read the wsdl and I got a working client with all the methods eating JSON, I was just blown away and happy! It's almost better than REST ;) But anyway.. THANK YOU for node-soap!

**Comment by jsdevel** [comment]
> Also just want to say I was a bit terrified to have to work with SOAP in my project. I wanted to try if Node.js could handle soap. And when it was just npm install soap, read the wsdl and I got a working client with all the methods eating JSON, I was just blown away and happy! It's almost better than REST ;) But anyway.. THANK YOU for node-soap!

@herom we should start a testimonial section in the README :laughing:

**Comment by herom** [comment]
@jsdevel yeah, with a "disclaimer" saying: "If you have to deal with SOAP - good luck" 😈

**Pull request merged**
