### PR TITLE
Adds commas and semicolons to listen(...) example

### PR DESCRIPTION
**Pull request by benjamin-albert**

### CODE REVIEW

**Comment by benjamin-albert** [comment]
I don't think the build is failing because of my changes to Readme.md

**Comment by jsdevel** [comment]
It's not.  It's failing because of a test related to an SSL certificate being expired.  For now, can you disable the test?

**Comment by jsdevel** [comment]
@benjamin-albert try rebasing and updating this PR.  I just commented out the failing test and will ping the author about it.

**Comment by benjamin-albert** [comment]
I've rebased the commit, looks like the tests pass now.

**Comment by jsdevel** [comment]
Thanks @benjamin-albert !

**Comment by benjamin-albert** [comment]
You're welcome.

**Pull request merged**
