### PR TITLE
Add support for xsd element ref

### PR DESCRIPTION
**Pull request by raymondfeng**
This PR adds the ability to handle XSD element ref.

### CODE REVIEW

**Comment by piscisaureus** [comment]
Amazing!

**Comment by raymondfeng** [comment]
@vpulim Can you review/merge the PR?

**Comment by piscisaureus** [comment]
cc @piscisaureus @dbrijesh

**Comment by raymondfeng** [comment]
@herom Can you review/merge the PR? We really want to have the problem fixed without a fork.

**Comment by lauort** [comment]
@raymondfeng  review our code, the checks needs to be correct.. if you have fails they will not merge the branch.

**Comment by jsdevel** [comment]
@raymondfeng I believe this can be merged once the checks pass.

**Comment by raymondfeng** [comment]
The tests are passing on all platforms except iojs.

**Comment by jsdevel** [comment]
@raymondfeng try updating the PR with the latest from master (`git pull --rebase upstream master`).  I just moved the `.travis.yml` file over to using docker.  That update _should_ trigger a Travis build, although it's been slow today.

**Comment by jsdevel** [comment]
Thanks for adding tetss @raymondfeng!  And this is amazing!

**Comment by jsdevel** [comment]
`v0.9.2` has been published with this change.

**Pull request merged**
