### PR TITLE
Add support for CDATA with text and CDATA with XML response

### PR DESCRIPTION
**Pull request by ugate**
Currently, when a response contains CDATA it's ignored. This PR adds a `sax.oncdata` function that handles responses with cdata text. Also, when cdata is encountered that contains xml it is converted to an object and made available in the result via `Data`.

### CODE REVIEW

**Comment by herom** [comment]
Thanks a lot for your contribution @ugate - we appreciate it a lot :+1: 

The PR is failing on the Travis CI build due to formatting errors, it would be necessary to run `npm test` locally on your project and update your code accoridingly. Also, a test for your code change would be much appreciated :+1: 

See our [Guidelines for Submitting a Pull Request](https://github.com/vpulim/node-soap/blob/master/CONTRIBUTING.md#submitting-a-pull-request) and don't hesitate to ask if you have any questions.

**Comment by ugate** [comment]
@herom we all good now?

**Comment by herom** [comment]
Looks all good @ugate - but there's just one thing left. If you look through the [Guidelines for Submitting a Pull Request](https://github.com/vpulim/node-soap/blob/master/CONTRIBUTING.md#submitting-a-pull-request) you'll see that 

>Pull Requests must be rebased to the latest version of master and squashed to a single commit ...

So, please, in order to get this merged it would be great if you could rebase and squash your commits into a single one (and please, don't close this PR and open a new one, it's solvable with `git` :+1: )

Thanks a lot!

**Comment by ugate** [comment]
@herom I'm not sure this is what you were looking for. Let me know. Thanks!

**Comment by herom** [comment]
@ugate now, you have 4 commits on your PR whereas we're looking for it to have just one commit per PR.

I'd suggest you make a "backup" of your local repository and try the following steps:

1) `git reset --hard HEAD~1` - removes the `Merge branch 'master' ...` commit as it's not needed anyhow
2) `git rebase -i HEAD~3` - this should open a `vi` instance and let you decide what to do with your commits. You will likely choose your first commit to be `pick`ed and the following to be `squash`ed. This let's you squash your commits into one (see [Github Help Pages](https://help.github.com/articles/about-git-rebase/) or [this tutorial](http://robots.thoughtbot.com/git-interactive-rebase-squash-amend-rewriting-history) for further explanation of the `interactive rebase`
3) Sync your fork with this `master` - again, see [Github Help for Syncing A Fork](https://help.github.com/articles/syncing-a-fork/) but instead of step 5 (`git merge upstream/master`) rebase it --> `git rebase upstream/master`.
4) Force push your squashed and rebased commits onto *your* remote repository

Try steps 1 to 3 after you made a backup and see if the outcome is what is expected (your fork updated to latest `master` and your single (squashed) commit on top of it). Use `gitk` for checking the git history frequently. *If anything goes wrong*, just overwrite it with your backup.

Sorry for the git odyssey, but otherwise we'll not be able to keep the git history of this project clean and traceable.

**Comment by ugate** [comment]
@herom I completely understand the odyssey :ok_hand:

I think I got it now. The last time I did it via SourceTree and I missed a few things. Sorry about the mistake and lack of following the contribution instructions :books:

**Comment by herom** [comment]
thanks a ton @ugate :+1:

**Pull request merged**
