### PR TITLE
Fix build in Node.js 18 by re-encrypting test key

### PR DESCRIPTION
**Pull request by e6c31d**
The encrypted private key test/certs/agent2-key-with-password.pem was encrypted with DES, which is unsupported in Node.js 18. I re-encrypted it with AES, and now the build works in Node.js 18.

### CODE REVIEW

**Comment by e6c31d** [comment]
I tried to fix the CI build by explicitly listening on `127.0.0.1` since the test is expecting that. I assume CI is defaulting to IPv6 so it was getting `::1` instead.

**Comment by jsdevel** [comment]
@e6c31d still failing

**Comment by e6c31d** [comment]
@jsdevel Can you re-run the build? I believe the build issue is fixed.

**Comment by RezaRahmati** [comment]
Hi @jsdevel 
Seems the other PR (https://github.com/vpulim/node-soap/pull/1212) is blocked by this, we appreciate if you can review and approve this

**Comment by e6c31d** [comment]
@jsdevel Sorry to ping you repeatedly, but can you please re-run the build and merge this PR?

**Pull request merged**
