### PR TITLE
Correctly add the https agent to axios

### PR DESCRIPTION
**Pull request by scagood**
According to the [axios Request Config](https://github.com/axios/axios#request-config) the agent needs to be passed using `httpsAgent`.

This is a follow up to https://github.com/vpulim/node-soap/pull/1146#issuecomment-889908849

### CODE REVIEW

**Comment by jsdevel** [comment]
@scagood please update with the latest from master.  i had to migrate to github actions.

**Comment by sm2017** [comment]
There is a bug in version Version 0.41.0, I am using Version 0.39.0 and it works well today I upgraded to latest version and found that there is a bug in my app, after inspecting I figured out that vpulim/node-soap#1154 is a bad PR, I am using https-proxy-agent package to send requests via a http proxy, the code works with proxy in version 0.39.0 but not latest (I am not testing 0.41.0 but I think the issue is here)

**Comment by sm2017** [comment]
@jsdevel @scagood please fix proxy bug

**Comment by scagood** [comment]
@sm2017 This is more likely another issue using axios, so you may want to start there (https://github.com/axios/axios/issues?q=is%3Aissue+is%3Aopen+https-proxy-agent) before making a PR to fix this.

**Comment by sm2017** [comment]
@scagood It was working before

**Pull request merged**
