### PR TITLE
replace request & httpntlm with axios & axios-ntlm

### PR DESCRIPTION
**Pull request by vision10**
This is my attempt to replace request and httpntlm packages with axios and axios-ntlm

Its not perfect yet and there are still some issues that need to be addressed:
- axios does not handle multipart options. 
  - axios recommends to use `form-data` package for attachments, but I don't know if we should include another package or let the user handle this
- `requestStream`  method does not return a request stream but a data response as a stream (because axios does not return the request stream, if only has the option to return the response as a stream with options.responseType='stream')
- a few tests need some rewriting (I have adjusted a few to work with the new packages as best as I knew/could)

I have updated a few packages (those with minor changes)
Some files have a few more changes because of vs code text autoformat (mainly whitespaces)
On a personal note, I don't think Promises mix well together with callbacks, so maybe callbacks should be dropped in a future version if axios is adopted ?

### CODE REVIEW

**Comment by jsdevel** [comment]
@vision10 please get the build to pass.

**Comment by j0k3r** [comment]
Something got broken with version 0.40.0 (I don't know if it's directly related to that PR).
I've tested to update the lib `soap-as-promised` and tests are failing.
- tests with soap 0.40.0: https://github.com/20minutes/soap-as-promised/runs/3008231406 ❌
- tests with soap 0.39.0: https://github.com/20minutes/soap-as-promised/runs/3008242162 ✅

**Comment by jsdevel** [comment]
@j0k3r can you submit a PR?

**Comment by j0k3r** [comment]
I didn't take a closer look atm. Maybe @vision10 can have an idea?

**Comment by vision10** [comment]
I think you need to use `createClientAsync` in your tests

**Comment by renanwilliam** [comment]
with this PR we lost support for sending attachments in MTOM?

**Comment by renanwilliam** [comment]
just to inform I have checked and we have a project MTOM attachments working fine on 0.39.0 and after upgrade to 0.40.0 it's stopped to work. This pull request is a breaking change.

**Comment by vision10** [comment]
Yes, I said it in the beginning, axios does not handle, attachments, and a decision is needed if we should include another pachage or let the user handle them

**Comment by renanwilliam** [comment]
Ok but isn't better decide it and implement before release it?

**Comment by j0k3r** [comment]
I agree this is a BC change, but before 1.0.0, everything can be broken.
What you should do @renanwilliam is
- revert to 0.39.0, 
- add a test unit to ensure MTOM attachements are working 
- let Dependabot create a PR with newest version (and fail for upgrading to 0.40.0)
- wait until a new version of node-soap pass your test and then you'll be able to merge it

**Comment by scagood** [comment]
I have just upgraded from `0.39.0` to `0.40.0` and for some reason the `ClientSSLSecurity` and `ClientSSLSecurityPFX` dont work anymore. 

This I can only assume it is associated to this PR :eyes:

**Comment by olliswe** [comment]
> I have just upgraded from `0.39.0` to `0.40.0` and for some reason the `ClientSSLSecurity` and `ClientSSLSecurityPFX` dont work anymore.
> 
> This I can only assume it is associated to this PR 👀

Same here...

**Comment by wagnerch** [comment]
SOAP faults also appear to be broken by this PR.

```
const soap = require("soap");

(async () => {
    const client = await soap.createClientAsync("http://www.dneonline.com/calculator.asmx?wsdl");

    try {
        const res = await client.AddAsync ({
            "intA": "1",
            "intB": "a"
        });
        console.log(res[0]?.AddResult);
    } catch (error) {
        console.log("ERROR:", error?.message);
    }
}) ();


C:> npm install soap@0.40.0
C:> node .\soap.js
ERROR: Request failed with status code 500

C:> npm install soap@0.39.0
C:> node .\soap.js
ERROR: soap:Client: System.Web.Services.Protocols.SoapException: Server was unable to read request. ---> System.InvalidOperationException: There is an error in XML document (1, 326). ---> System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at System.Xml.XmlConvert.ToInt32(String s)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReader1.Read1_Add()
   at Microsoft.Xml.Serialization.GeneratedAssembly.ArrayOfObjectSerializer.Deserialize(XmlSerializationReader reader)
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle)
   at System.Web.Services.Protocols.SoapServerProtocol.ReadParameters()
   --- End of inner exception stack trace ---
   at System.Web.Services.Protocols.SoapServerProtocol.ReadParameters()
   at System.Web.Services.Protocols.WebServiceHandler.CoreProcessRequest()
```

**Comment by wagnerch** [comment]
@scagood Yeah, unfortunately I use axios, and it is also used in Azure which I also use, so setting this as a default wouldn't work for me.  Not sure what the scoping of this default would be?  I don't think the exception behavior should change because the underlying HTTP engine has changed.

I'll stick on 0.39.0 for now, and see where things go.

**Comment by wagnerch** [comment]
@scagood Thanks for the tip, submitted a PR to fix it.

**Comment by bigplayalman** [comment]
for anyone having an issue with this, since this is using axios you need to change your options

`
import https from 'https';

const agent = new https.Agent({
  rejectUnauthorized: false,
  pfx: 'pfx buffer',
  passphrase: 'password',
})

  const options = {
    wsdl_options: {
      httpsAgent: agent,
    }
}`

**Comment by isaacgrimaldo** [comment]
other way to use it 

```
const agent = new https.Agent({
    cert: certpub,
    key: certpri,
  });

  const options = {
    envelopeKey: 'soapenv',
    wsdl_options: {
      httpsAgent: agent,
    },
  };
```

**Pull request merged**
