### PR TITLE
Prevent duplicate declaration for namespace prefix

### PR DESCRIPTION
**Pull request by fredmon3**
Without this change, node-soap may inject duplicate declarations into the same xml node.

### CODE REVIEW

**Comment by rjkeller** [comment]
Awesome fix! I ran into the issue of duplicate declarations and this does the trick!

What does it take to get this merged?

**Comment by rjkeller** [comment]
@herom Are you able to merge this PR? It fixes a pretty big issue with node-soap.

**Comment by jsdevel** [comment]
We need some request-response samples.  @fredmon3 can you add some?

**Comment by albinekb** [comment]
@jsdevel I bumped in to a problem that this PR fixed, what samples do you need and in what format?

**Comment by albinekb** [comment]
Ping again :) @jsdevel

**Comment by jsdevel** [comment]
@albinekb tests are needed

**Comment by fredmon3** [comment]
@jsdevel, I can build the tests for this in a similar fashion to the **request-response-samples**.  Where should I actually place the tests that I generate in the repo?

**Comment by jsdevel** [comment]
@fredmon3 you'll see examples under `test/`.

**Comment by jsdevel** [comment]
closing due to inactivity

**Pull request closed without merging**
