### PR TITLE
Add last endpoint

### PR DESCRIPTION
**Pull request by rfink**
Addresses #650

### CODE REVIEW

**Comment by herom** [comment]
Thanks a lot for your effort @rfink - I restarted the tests over at Travis CI and they fail when run on `io.js`. Would it be possible for you to run the tests locally at `io.js` and see what's going on so that we can merge this in? This would be awesome :+1:

**Comment by rfink** [comment]
Ha, forgot about iojs (I'm such a dinosaur).  Do you know what version of iojs your build runs?  I just ran it locally with 1.6.1 (via NVM) and all passed.  I'm going to download the latest right now and try again.

**Comment by rfink** [comment]
Just confirmed working again with iojs 2.0.2 (via NVM)

**Comment by herom** [comment]
@rfink I restarted the Travis CI build again (it's running on latest `io.js`, so `v2.0.2`) and it's still failing :cry:

**Comment by rfink** [comment]
Bummer.  I'll pull down the latest changes from master, merge them, and try again.

**Comment by herom** [comment]
ping @rfink - did you have some time to check this?

**Comment by rfink** [comment]
Hey herom, I tried this locally a few times over the weekend, including in a fresh docker environment, and I've been unable to reproduce the errors.  I'm not really sure what's happening, these errors don't look to be related to the change, although I'm unable to verify.  What's your suggestion?

**Comment by herom** [comment]
Never mind, I had to restart the tests several (more than 10x) times over at Travis CI, now the tests pass... let's see how long it takes when it gets merged in :smile_cat:

**Comment by rfink** [comment]
Hey, sounds great.  I've had a few issues with Travis CI as well recently.  Thanks again!

**Pull request merged**
