### PR TITLE
Add typescript support

### PR DESCRIPTION
**Pull request by onury**
Added types file for all exported public members of soap.

### CODE REVIEW

**Comment by aleung** [comment]
It's good to bundle TypeScript typing in package than maintain separately in `@types/node-soap`. TypeScript 1.x doesn't support bundling at the time when Nicole and me created the typing in https://github.com/DefinitelyTyped/DefinitelyTyped/. I'll remove it from DefinitelyTyped once typing is shipped in `node-soap` package.

@onury I don't intend to continue the code style war from https://github.com/DefinitelyTyped/DefinitelyTyped/pull/18511 to here. Could you add aliases  `Security`, `SoapMethod` and `Option` so it won't break existing users of `@types/node-soap`?

**Comment by onury** [comment]
@aleung just added.

**Comment by herom** [comment]
@onury as I guess, this is an ongoing WIP am I right?

If so, would it be possible for you to notify us when this PR is "ready"? Thanks 👍

**Comment by onury** [comment]
@herom it's ready actually. I've just added support for node-soap v0.20.0 release.

**Comment by herom** [comment]
ah, I see 😺 

what do you think @jsdevel, ready for merge? 💯

**Comment by herom** [comment]
@aleung would you mind checking if this PR also suits your request

> Could you add aliases Security, SoapMethod and Option so it won't break existing users of @types/node-soap?

👍

**Comment by aleung** [comment]
@herom OK for me.

**Comment by herom** [comment]
thanks a lot @onury @aleung 👍

**Comment by aleung** [comment]
Waiting for a release which includes typings: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/18858

**Pull request merged**
