### PR TITLE
Upgrade formidable to v2

### PR DESCRIPTION
**Pull request by orgads**
v1 is deprecated.

### CODE REVIEW

**Comment by orgads** [comment]
@vpulim ping

**Comment by orgads** [comment]
The failure doesn't look related to my change. It looks the same as in #1180.

**Comment by jsdevel** [comment]
@orgads i know you didn't cause it.  i'm mainly a PR reviewer and publisher.  if you have time to fix it on master i'd greatly appreciate it

**Comment by alfaproject** [comment]
The update to this version now breaks our webpack build and accordingly to formidable, updating to version 3 fixes the issue. Is there any reason why you didn't choose to update to version 3 instead?

**Comment by orgads** [comment]
I used `latest`. Wasn't aware of v3 (which is still not `latest` at this point).

**Comment by alfaproject** [comment]
Fair enough, I've followed up with their team to see what's the status. Thanks!

**Comment by kvetoslavnovak** [comment]
After upgrading to 0.45.0 there seems to be breaking change for me. 
node-soap v 0.45.0 update broke soap.createClientAsync()

I am not able to track were the problem might be. , see the description of the problem here in Stackoverflow:
[node-soap v 0.45.0 update broke soap.createClientAsync()](https://stackoverflow.com/questions/74339110/node-soap-v-0-45-0-update-broke-soap-createclientasync)

**Pull request merged**
