### PR TITLE
[FIX] [DO NOT MERGE] Possible fix #933 (regression because of introduction of new be…

### PR DESCRIPTION
**Pull request by herom**
…haviour in #914)

This is very much "work in progress", so please feel free to review/comment/contribute until it's ready to merge and ready to use 😺

### CODE REVIEW

**Comment by herom** [comment]
What's sad about this is, that we'd have a tradeoff and introducing yet another "option" which may or may not get passed to the `createClient()` method, but I couldn't think of any better solution in order to prevent the client from forcing the sequencing behaviour which was introduced earlier and broke our latest release - which means it made it unusable for a lot of users.... 😞

**Comment by herom** [comment]
can I have your opinion on this fix @jsdevel ? 😸

**Comment by jsdevel** [comment]
I don't think an option for this is good.  Perhaps we should just revert https://github.com/vpulim/node-soap/pull/914.  Do we know what releases that PR made it into?

**Comment by jsdevel** [comment]
https://github.com/vpulim/node-soap/pull/937

**Comment by herom** [comment]
Closing due to #937

**Pull request closed without merging**
