### PR TITLE
Fixed PasswordDigest Generation

### PR DESCRIPTION
**Pull request by martinholden-skillsoft**
The WSSE password digest is best calculated from a byte array of the concat of NONCE, CREATED TIMESTAMP and PASSWORD

### CODE REVIEW

**Comment by jsdevel** [comment]
please provide tests and fix the build

**Comment by jsdevel** [comment]
Please fix the build

**Comment by martinholden-skillsoft** [comment]
> Please fix the build

I am not sure what you want me to fix, none of the issues appear to be in any of the files I have touched

**Comment by jsdevel** [comment]
have you rebased your branch onto master?

**Comment by martinholden-skillsoft** [comment]
> have you rebased your branch onto master?

Yes, just did it again now and no changes. The Travis build is reporting an error in code I haven't touched on Node 6
 
  1 failing
  1) SOAP Server
       should properly handle compression:
      Uncaught AssertionError: false == true
      + expected - actual
      -false
      +true

**Comment by martinholden-skillsoft** [comment]
> > have you rebased your branch onto master?
> 
> Yes, just did it again now and no changes. The Travis build is reporting an error in code I haven't touched on Node 6
> 
> 1 failing
> 
> 1. SOAP Server
>    should properly handle compression:
>    Uncaught AssertionError: false == true
>    
>    * expected - actual
>      -false
>      +true

I refactored the failing test for the compression check that wasnt mine :-)

**Comment by jsdevel** [comment]
thanks @martinholden-skillsoft !

**Pull request merged**
