### PR TITLE
Support messages with multiple parts and handle nested includes

### PR DESCRIPTION
**Pull request by devongovett**
Sorry for the huge PR, it's mostly test changes. This fixes two things: messages with multiple parts (#467), and processing of nested includes. These were both issues I saw working with [Sabre's WSDL](http://wsdl-crt.cert.sabre.com/sabreXML1.0.00/usg/SessionCreateRQ.wsdl). For example, the GetSessionCreateInput message element has three parts. For the nested includes issue, the import for SessionCreateRQRS.xsd in turn needs to include SessionCreateRQ.xsd and SessionCreateRS.xsd. I've added a request-response test that tests both of these issues. The other test changes are a result of the WSDL parser now parsing includes recursively. I copied the missing XSD files into the test folders.

### CODE REVIEW

**Comment by devongovett** [comment]
Tests pass locally and in one of the builds on Travis. Not sure why the other one failed. Any idea? Is there a way to rerun them there?

**Comment by herom** [comment]
Thanks a lot for your contribution @devongovett - we really appreciate it a lot! :+1:  (I restarted the Travis Build and all tests passed).

As I see that all of your commits are related somehow I understand that you opened one PR for all of them, but this makes it rather hard for us to keep track of the library changes (especially because you fixed more than one issue that could be also be a "standalone" PR).

I'd like to hear @jsdevel s opinion on this as the fixes seem very valuable, but if we really go through the process of ripping the PR apart into several smaller PRs I guess you will probably get annoyed and I don't want to see this PR orphaned or unmerged because of a to complex/complicated `git` issues :cactus:

In the meanwhile (in order to prepare you of what you might expect :smiley:) I leave here the link to our [Guidlines on Submitting a Pull Request](https://github.com/vpulim/node-soap/blob/master/CONTRIBUTING.md#submitting-a-pull-request) - most of it is already met, except the "one commit per pull request" rule :smiley:

**Comment by devongovett** [comment]
Yes, I was originally going to submit two PRs but the tests I added using Sabre's WSDL depended on both fixes. I could split it into three if you want. Let me know, otherwise I'll squash the commits.

**Comment by devongovett** [comment]
Bumping this. Let me know how we should proceed. Thanks!

**Comment by herom** [comment]
Hello @devongovett 
I'm very busy these days so please excuse my delay on answering. I thought that it might be a good idea to ask @jsdevel for his opinion on this rather big PR as he is the lead maintainer, but I haven't heard of him for a while now.  So, it seems that we're "on our own" now :smile: 

First off, thanks again for your work and your contribution, I appreciate it a lot!

Here are some thoughts of mine after I cloned your fork (github won't show me the whole commits), please feel free to discuss these points, they are not "written in stone" but they seem reasonable to me:

- I would prefer if you could split your PR so that the first batch of of commits (`Recursively process includes`, `Add all nested include test files`) is packed into one commit/PR, `Make tests run faster by including local xml` & `Allow setting namespace and xmlns for headers in tests` could be squashed into a single commit for testing performand and have it's own PR, as well as `Support message elements with multiple parts. Fixes #467` & `Add request-response test for multiple parts and recursive includes` could also be squashed into a single PR/commit I guess.

- Is it possible for you to add smaller files within your `Add all nested include test files` commit? For example `addList__complex_extension_namespace_for_arrays/soap.platform.commonTypes.xsd` is really bloated with a huge number of `<enumeration/>`s for the containing simple types - would it be possible to limit the number of these childNodes to a maximum of 2 - 3? The same goes a along for the `soap.platform.common.xsd`, `soap.platform.fautlTypes.xsd` and so on. I think all the testcases should also be possible to create with way smaller `xsd`s. As I saw (or at least I guess - this commit is so huge that I'm a bit lost) that you included the same files in nearly all of the test directories I wonder if it would be possible to put them in another directory and reference them from there, so we don't have to copy these big files for each and every test.
I guess you're using the full Sabre WSDL but I think copying them for each and every test is just a huge overkill.

What do you think?

**Comment by jsdevel** [comment]
@devongovett sorry, but this PR is simply too big.  The github UI wouldn't even display the diff.  Please issue smaller more targetted PRs as suggested by @herom.

@herom sorry for the hiatus.  Holidays :P

**Comment by herom** [comment]
@devongovett are you interessted in getting this huge amount of work merged? I would love to see this enhancement in `node-soap` :+1:

**Comment by devongovett** [comment]
Yes I would like to, just need to find time to separate things out as requested.

**Comment by antonimmo** [comment]
This is EXACTLY the fix I need. Working with the same service. Have you already merged it?

This is what I get when issuing "console.log(util.inspect(client.describe(), false, null))":

{ SessionCreateRQService: 
   { SessionCreatePortType: 
      { SessionCreateRQ: 
         { input: { undefined: undefined, 'undefined[]': undefined },
           output: { undefined: undefined, 'undefined[]': undefined } } } } }

**Pull request closed without merging**
