### PR TITLE
fix: invalid multipart/related Content-Type

### PR DESCRIPTION
**Pull request by sandrozbinden-axa**
According to rfc 2384 (https://www.ietf.org/rfc/rfc2387.txt) the multipart/related Content-Type syntax allows only one `type`field 

The change with pr (https://github.com/vpulim/node-soap/pull/1173) changed the correct `start-info` field to `type`. This causes strict soap servers to reject the request because the `type` is now duplicated and with different values.

This small pr reverts the change to `start-info`

### CODE REVIEW

**Comment by sandrozbinden-axa** [comment]
@jsdevel Do you have time to review this issue? It is preventing us from updating to the latest node-soap Version

**Comment by benasher44** [comment]
Hi! I have no merge privileges in this repo, unfortunately

**Comment by sandrozbinden-axa** [comment]
Hi @benasher44. Thanks a lot for your quick reply. Do you know anyone with merge privileges? I wasn't really successful with contacting any of the Maintainers listed in the README.

**Comment by benasher44** [comment]
I dont, sorry! I would recommend using something like patch-package or yarn patch, if you're on yarn 2+ to unblock your local project with this change, for the time being.

**Comment by sandrozbinden-axa** [comment]
Hi @w666 

I noticed you've been actively merging PRs lately. Could you please review this one? It's a small fix to ensure compliance with RFC 2384.

**Comment by benasher44** [comment]
Also would it be possible to reopen the issues tab? I think closing all issues and declaring issue bankruptcy would be preferable to just blocking all issues

**Review by w666 — APPROVED** [review]

**Comment by w666** [comment]
Hi @sandrozbinden-axa, when do you need this change?

**Comment by sandrozbinden-axa** [comment]
Hello @w666,

We are currently using a forked version of this package. We would prefer to switch back to the original package, so we are hoping for a new release in the near future. It’s not urgent, but it would be greatly appreciated.

Thank you for your efforts!

**Comment by w666** [comment]
@benasher44 I don't think I have permissions to enable issues tab. I will ask project owner if I remember about it.

**Comment by w666** [comment]
@sandrozbinden-axa I will have a look on other changes that may be included into next release. Feel free to suggest pull-requests that maybe useful. I will try to release new version later this week or early next week, but depends on free time.

Thanks for pointing out on changes that are needed by community.

**Pull request merged**
