### PR TITLE
issue: Replace deprecated "request"

### PR DESCRIPTION
**Pull request by TrySound**
Openning dumb PR as issues are not available.

"request" package is deprecated.

https://github.com/request/request#deprecated

A few possible alternatives
- https://github.com/node-fetch/node-fetch
- https://github.com/axios/axios
- https://github.com/sindresorhus/got

### CODE REVIEW

**Comment by m-abs** [comment]
I'd be willing to do the work next week, if I can use `cross-fetch` and make a few other minor changes to make `node-soap` more browser friendly.

**Comment by m-abs** [comment]
I've started working on it here:
https://github.com/m-abs/node-soap/tree/feat/replace-requestjs

I'll make a PR once I finish the work.

**Comment by jsdevel** [comment]
i'd prefer axios, as it's widely used

**Comment by giovanni-bertoncelli** [comment]
Any chance that requestjs will be replaced in the near future?

**Comment by TrySound** [comment]
@giovanni-bertoncelli It's quite hard to do because request options are exposed as public api. Though maintainers are open for contributions.

**Comment by jsdevel** [comment]
PRs are welcome!

**Comment by SteinRobert** [comment]
Hey - I'm willing to look into this issue @TrySound 

Just a few questions before I start working in the wrong direction:

1. Are you willing to break backwards compatibility - as you've pointed out request's API is directly exposed within node-soap.
2. Would `axios` be your preferred choice as a library? It would come in quite handy for me since I'm pretty familiar with `axios`. However, I'm fine with any other library (given it has at least some documentation).

**Comment by TrySound** [comment]
@SteinRobert I'm not maintainer of this project. But I guess it's ok to bump major version especially in non-semver. See comment https://github.com/vpulim/node-soap/pull/1108#issuecomment-614312501

**Comment by SteinRobert** [comment]
Oh sorry - @jsdevel would you mind answering my questions from https://github.com/vpulim/node-soap/pull/1108#issuecomment-824172387 ?

**Comment by jsdevel** [comment]
sorry for the late reply.  breaking backwards compatibility is important, but if the change isn't _too_ breaking we can consider it.

**Pull request closed without merging**
