### PR TITLE
processRequestXml only if req.body is not empty object

### PR DESCRIPTION
**Pull request by amity0**
When using `bodyParser.json()` I get empty req.body object which translate to [Object object] and throws exception 
"Non-whitespace before first tag.\nLine: 0\nColumn: 1\nChar: ["

This PR only uses processRequestXml if req.body is not empty

### CODE REVIEW

**Comment by amity0** [comment]
@jsdevel which file would you say is a good place to add a test? 

Thanks

**Comment by jsdevel** [comment]
please study the current tests and decide the best approach.

**Comment by amity0** [comment]
@jsdevel I added a test. let me know what you think

**Comment by jsdevel** [comment]
thanks!

**Pull request merged**
