### PR TITLE
Fix build by satisfying jshint indentation

### PR DESCRIPTION
**Pull request by pihvi**
I also got this https://github.com/vpulim/node-soap/pull/914#issuecomment-282198924
when running npm test and build failed. Now it passes.

### CODE REVIEW

**Comment by herom** [comment]
I tried to restart the build over at travis, but it's failing due to `npm` and `node.js` version collision in build-tests for `0.1x` and `0.12.x`. 

I think, as we're now writing the year 2017 for half a year now, and `4.x` being LTS for quite a good time now, we should drop the build-tests for these obsolete versions. I'll open up a PR for this, so that it's easy to follow the decission and implementation/drop. 

What's your opinion on this @jsdevel ?

**Comment by herom** [comment]
@pihvi as we dropped the support for the "methusalem" `node.js` versions, would you mind rebasing your branch so that we can run the tests without the legacy tests being around? thanks a ton 👍

**Comment by pihvi** [comment]
After this update (without this patch) I still get this running "npm test" locally:

```
HEAD is now at 1a440a0... Drop `travis-ci` test support for `node.js` < `4.x` (LTS) (#932)
➜  node-soap  npm test

> soap@0.19.0 pretest /Users/amattila/oma/Dropbox/code/node-soap
> jshint index.js lib test

test/sequence-test.js: line 53, col 5, Expected '}' to have an indentation at 7 instead at 5.
test/sequence-test.js: line 55, col 1, Expected '}' to have an indentation at 3 instead at 1.

2 errors
npm ERR! Test failed.  See above for more details.
```

And this PR fixes that i.e. "npm test" locally.

**Comment by pihvi** [comment]
@herom so now this is rebased.

**Comment by herom** [comment]
awesome 👍

**Comment by herom** [comment]
I have no idea why running `npm test` on a local machine triggers our `pretest` command while it doesn't on `travis`... I'd have to take a thorough look at it as running `jshint` is crucial in my opinion...

**Comment by jsdevel** [comment]
What version of mom @pihvi?

**Comment by jsdevel** [comment]
Mom === npm (autocomplete on a phone)

**Pull request merged**
