### PR TITLE
preserve whitespace for space only text node: <text> </text>

### PR DESCRIPTION
**Pull request by yffrankwang**
when preverseWhitespace = true option is specified, the space in the text node should be preversed.
but if the text node's content is all white space, these space is not preserved. 
example: <text> </text>
expect: result.text = ' ' (<- one space)
actual: result.text = ''  (empty string)

### CODE REVIEW

**Comment by w666** [comment]
Could you please add tests for this change?

**Comment by yffrankwang** [comment]
test/response-preserve-whitespace-test.js

**Comment by w666** [comment]
Looks like new test failed, could you please have a look? Thanks.

**Comment by yffrankwang** [comment]
both test/client-response-options-test.js test/response-preserve-whitespace-test.js  use 'test/wsdl/hello.wsdl' to create soap client.
the two soap client instance's schema are different, this cause the secondary test failed.
i don't know why, this may be another bug.

please take a look at the following test.

>mocha test/response-preserve-whitespace-test.js
```
  Preverse whitespace
    ✔ preserves leading and trailing whitespace when preserveWhitespace option is true


  1 passing (39ms)
```

>mocha test/client-response-options-test.js  test/response-preserve-whitespace-test.js
```

  SOAP Client
test server is created
test server is listening in http://127.0.0.1:54454
client created: { Hello_Service: { Hello_Port: { sayHello: [Object] } } }
api finished in ms: 19
    ✔ lastElapsedTime is computed
server is closed

  Preverse whitespace
    1) preserves leading and trailing whitespace when preserveWhitespace option is true


  1 passing (2s)
  1 failing

  1) Preverse whitespace
       preserves leading and trailing whitespace when preserveWhitespace option is true:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (D:\Develop\Projects\frank\node-soap\test\response-preserve-whitespace-test.js)
      at listOnTimeout (internal/timers.js:557:17)
      at processTimers (internal/timers.js:500:7)
```

**Comment by w666** [comment]
I am not sure why you get timeout error, but I cloned your repo and run the test, I got the same probem as in pipeline
image

Seems like it does not work?

**Comment by yffrankwang** [comment]
because the assertion in the test case failed, and the following `done()` is not called, so the timeout error occurred.
```
              assert.equal(' ', result.greeting);
              done();
```

**as i commented yesterday, if you run the single test case, it will passed.**
> mocha test/response-preserve-whitespace-test.js
```
  Preverse whitespace
    ✔ preserves leading and trailing whitespace when preserveWhitespace option is true
  1 passing (39ms)
```

**but if you run the following 2 test case together, the second test case will failed.**
> mocha test/client-response-options-test.js test/response-preserve-whitespace-test.js

```
SOAP Client
test server is created
test server is listening in http://127.0.0.1:54454
client created: { Hello_Service: { Hello_Port: { sayHello: [Object] } } }
api finished in ms: 19
    ✔ lastElapsedTime is computed
server is closed

  Preverse whitespace
    1) preserves leading and trailing whitespace when preserveWhitespace option is true


  1 passing (2s)
  1 failing

  1) Preverse whitespace
       preserves leading and trailing whitespace when preserveWhitespace option is true:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (D:\Develop\Projects\frank\node-soap\test\response-preserve-whitespace-test.js)
      at listOnTimeout (internal/timers.js:557:17)
      at processTimers (internal/timers.js:500:7)
```

The reason why the second test case failed is that the two test cases use 'test/wsdl/hello.wsdl' to create soap client.
The first soap client is correct, but the second soap client is incorrect.

The **cur.schema** in the following code is different.
The first soap client **cur.schema** is string, but the second soap client **cur.schema** is null.

https://github.com/vpulim/node-soap/pull/1211/files#diff-2c1300f4732a4bdd2d6f0234d611bb7ac264b39f5a173b4f86412a26102b0258R358

image

i don't know why the second soap client is different from the first soap client, this may be another bug.

**Comment by w666** [comment]
I think this is useful change, but working tests are required for that. I am happy to accept this when all tests pass. Thanks.

**Review by w666 — APPROVED** [review]

**Comment by w666** [comment]
Thanks for fixing the test. I will include this in next release. Thanks.

**Pull request merged**
