### PR TITLE
upgraded xml-crypto to latest version

### PR DESCRIPTION
**Pull request by Kifah**
Upgrading `xml-crypto` extension, in order to avoid a severe vulnerability reported by GitHub.
Bildschirmfoto 2020-10-28 um 16 51 48

### CODE REVIEW

**Comment by juuxstar** [comment]
👍

**Comment by manishgadhock-monotype** [comment]
Awaiting for this change. +1

**Comment by atishayjain** [comment]
+1

**Comment by gaurkeshav** [comment]
+1

**Comment by jsdevel** [comment]
thank you!

**Comment by mllanes** [comment]
It seems this change didn't make it to v 0.34.0?

**Comment by danleegion** [comment]
Package version should be updated with 0.34.1 or 0.35.0 as NPM was not updated due to version

**Comment by jansenlau** [comment]
Any idea on when a new package version update that includes this change will be available?

**Comment by jsdevel** [comment]
0.35.0 has it

**Comment by marjandjokic** [comment]
Hi, I have problem when switching to version 0.35.5 of node-soap as now request are sent without body.const client = await createClientAsync(serviceConfig.wsdl, soap_client_options);
const result = await client.healthCheckAsync();
This works well with 0.32.0 but not with 0.35.0 I see my request has empty bodies. Any idea what needs to be done, maybe some additional options?

Thanks in advane

**Comment by marjandjokic** [comment]
> Hi, I have problem when switching to version 0.35.0 of node-soap as now request are sent without body.const client = await createClientAsync(serviceConfig.wsdl, soap_client_options);
> const result = await client.healthCheckAsync();
> This works well with 0.32.0 but not with 0.35.0 I see my request has empty bodies. Any idea what needs to be done, maybe some additional options?
> 
> Thanks in advance, Marjan

I noticed that when I don't send any parameters in method like I do above: const result = await client.healthCheckAsync();
Then request looks like: (Request method is ommited)
<?xml version=\"1.0\" encoding=\"utf-8\"?>
<soap:Envelope...>
	<soap:Body></soap:Body>
</soap:Envelope>
But If I add some dummy parameters then all good, I fixed it like that, but I just wonder if that can be done in some better way.

**Pull request merged**
