### PR TITLE
Need to obtain URL path from incoming soap request

### PR DESCRIPTION
**Pull request by fyatzeck**
As a solution to issue #643, I am proposing an update to server.js to invoke soap service function with
additional argument to provide URL path from incoming request.

I have tested soap requests with new "pathName" field in updated function callback and successfully received value as expected by my service function.

### CODE REVIEW

**Comment by herom** [comment]
Hello @fyatzeck - thanks a lot for your contribution. :+1: 

Please, see our [Guidelines on Submitting a Pull Request](https://github.com/vpulim/node-soap/blob/master/CONTRIBUTING.md#submitting-a-pull-request) and go through the steps mentioned there in order to get your PR fixed. Namely, the steps which prevent me from merging the PR are:

- Add accompanying tests.
- Merge/rebase your commits so that your PR consists of just **one** commit and rebase it on the current **master** branch

**Comment by fyatzeck** [comment]
As requested, here is a summary of my test results using a simple test wsdl, I tried to attach xml formatted results in original comment but xml did not properly show but now know how to post xml:

Test endpoint URL:
http://localhost:8080/SayHello

First, I tested with the new service callback API:
	sayHello: function(args, callback, soapHeader, pathName)

Output below correctly shows pathname request was received on:

Handling POST on /SayHello
received
```
<soapenv:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:urn="urn:examples:helloservice">
   <soapenv:Header/>
   <soapenv:Body>
      <urn:sayHello soapenv:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
         <firstName xsi:type="xsd:string">Fred</firstName>
      </urn:sayHello>
   </soapenv:Body>
</soapenv:Envelope>
```
info
Attempting to bind to /SayHello
info
Trying Hello_Port from path /SayHello
```
The following is console log from my callback:

Got Hello request from {"attributes":{"xsi:type":"xsd:string"},"$value":"Fred"} 

ON PATH NAME : /SayHello
```
replied
```
<?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"  xmlns:tns="http://localhost:8000/wsdl/HelloService.wsdl"><soap:Body><tns:sayHelloResponse><firstName>Fred</firstName></tns:sayHelloResponse></soap:Body></soap:Envelope>
```

Then, I tested backward compatibility with the existing service callback API only expecting "args" :
	sayHello: function(args)

Output below shows pathname request was received on as "null" without any impact to the service call and response:

Handling POST on /SayHello
received
```
<soapenv:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:urn="urn:examples:helloservice">
   <soapenv:Header/>
   <soapenv:Body>
      <urn:sayHello soapenv:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
         <firstName xsi:type="xsd:string">Fred</firstName>
      </urn:sayHello>
   </soapenv:Body>
</soapenv:Envelope>
```
info
Attempting to bind to /SayHello
info
Trying Hello_Port from path /SayHello
```
The following is console log from my callback:

Got Hello request from {"attributes":{"xsi:type":"xsd:string"},"$value":"Fred"} 

ON PATH NAME : null
```
replied
```
<?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"  xmlns:tns="http://localhost:8000/wsdl/HelloService.wsdl"><soap:Body><tns:sayHelloResponse><firstName>Fred</firstName></tns:sayHelloResponse></soap:Body></soap:Envelope>
```

**Comment by fyatzeck** [comment]
As per merge/rebase instructions, I am really not clear how to merge/rebase from my forked repo fyatzeck:master, please advise.

**Comment by jsdevel** [comment]
closing for lack of activity

**Pull request closed without merging**
