### PR TITLE
Bumped xml-crypto version to ">=4.0.1"

### PR DESCRIPTION
**Pull request by parallels999**
Any help??

### CODE REVIEW

**Comment by vision10** [comment]
just bumping xml-crypto to v4 without other modifications will currently break existing code
it cannot be updated without code & maybe tests changes

**Comment by parallels999** [comment]
> just bumping xml-crypto to v4 without other modifications will currently break existing code

yes, it does, 

>Any help??

**Comment by parallels999** [comment]
xml-crypto already on V6

**Comment by w666** [comment]
Hi @parallels999, if you can update it to version 6, I am happy to review and merge it. Thanks.

**Comment by w666** [comment]
I am testing new changes with updated deps, including xml-crypto 6. Closing this PR as it is inactive.

**Pull request closed without merging**
