### PR TITLE
Added namespace to array elements

### PR DESCRIPTION
**Pull request by StfMond**
objectToXML not serialize correctly array elements, It needed namespaces too

### CODE REVIEW

**Comment by herom** [comment]
Thanks a lot for your contribution @StfMond - we appreciate it a lot 👍 

Please see the failing tests over at our Travis CI build and try to fix them before we can merge your PR. Also, we require at least 1 test (here, a `request/response sample test` would be the best thing) in order to accept and merge your PR (see [Guidelines on Submitting a Pull Request](https://github.com/vpulim/node-soap/blob/master/CONTRIBUTING.md#submitting-a-pull-request))

**Comment by jt55401** [comment]
@StfMond  - we're also running into this issue.  Please let me know if I can do anything to help move this forward.

**Comment by jsdevel** [comment]
why did it need this?  unless you're planning on referencing the namespace prefix, it really isn't needed right?

tests are failing.

**Comment by hallvors** [comment]
I think I ran into this bug. I need to generate this XML (snippet):
```
<pay:InvoiceRows>
  <inv:InvoiceRow> …. </inv:InvoiceRows>
  <inv:InvoiceRow> …. </inv:InvoiceRows>
</pay:InvoiceRows>
```
and attempted to set `namespaceArrayElements: false` in wsdlOptions and pass in this (part of larger object):
```
{ 'pay:InvoiceRows': [
  {'inv:InvoiceRow': … },
  {'inv:InvoiceRow': … },
]}
```
but to my surprise node-soap serializes that as
```
<InvoiceRows>
  <inv:InvoiceRow> …. </inv:InvoiceRows>
  <inv:InvoiceRow> …. </inv:InvoiceRows>
</InvoiceRows>
```
Note how the outer element is missing the expected name space prefix.

**Comment by StfMond** [comment]
@jt55401 Thanks for your offer, I need to generate at least 1 test to pass tests over Travis Build

**Comment by StfMond** [comment]
@herom Thank for you reply I'm work on that.

**Comment by StfMond** [comment]
@jsdevel currently the serialization puts the prefix in the other types of objects but not in aray elements this generate an error when the service revieves the request.

**Comment by erwinlobos** [comment]
hi, do you have a solution for this issue?

**Comment by jsdevel** [comment]
@erwinlobos we either need this PR to be updated as requested previously, or we need a new PR.

**Pull request closed without merging**
