### PR TITLE
Fixed some issues with xsd elements

### PR DESCRIPTION
**Pull request by zanemcca**
- Namespace was not fetched properly when `definitions.xmlns[type.prefix]` is `undefined`. There appears to be a small typo in the logic that was fixed. Please comment if this logic was intentional and we can discuss it.
- Some types are still strings when the `defaultsDeep` is called. Explicitly checking for strings before calling `defaultsDeep` resolves the issue

### CODE REVIEW

**Comment by jsdevel** [comment]
please fix the build

**Comment by zanemcca** [comment]
I updated the first patch to be more specific to the particular use case. I am a `node-soap` newb so any input on the fix would be appreciated.

**Comment by jsdevel** [comment]
can you add a test?

**Comment by zanemcca** [comment]
Test added :)

**Comment by jsdevel** [comment]
thanks!

**Comment by zanemcca** [comment]
Thank you @jsdevel! When should I expect this to be published?

**Comment by jsdevel** [comment]
we're due for a publish soon.  i may have time in the next few days

**Pull request merged**
