### PR TITLE
Upgrade dependencies and refactor code to work with the latest xml-crypto

### PR DESCRIPTION
**Pull request by w666**
Refactor WSSecurityCert and WSSecurityCertWithToken to make it
 work with the latest xml-crypto.

 Fix invalid test xml strings in WSSecurityCert and
 WSSecurityCertWithToken tests.

 Update dependencies:
 - axios to 1.7.2
 - debug to 4.3.5
 - formidable to 3.5.1
 - sax to 1.4.1
 - uuid to 10.0.0
 - whatwg-mimetype to 4.0.0
 - xml-crypto to 6.0.0

 Update dev dependencies:
 - @types/debug to 4.1.12
 - @types/express to 4.17.21
 - @types/lodash to 4.17.5
 - @types/node to 14.0.0
 - @types/request to 2.48.12
 - @types/sax to 1.2.7
 - @types/uuid to 9.0.8
 - @types/whatwg-mimetype to 3.0.2
 - body-parser to 1.20.2
 - colors to 1.4.0
 - diff to 5.2.0
 - doctoc to 2.2.1
 - duplexer to 0.1.2
 - express to 4.19.2
 - finalhandler to 1.2.0
 - glob to 10.4.1
 - jshint to 2.13.6
 - mocha to 10.4.0
 - nyc to 17.0.0
 - semver to 7.6.2
 - serve-static to 1.15.0
 - sinon to 18.0.0
 - source-map-support to 0.5.21

### CODE REVIEW

**Comment by vision10** [comment]
`request` package was removed so you cand also remove `@types/request`

**Comment by kouak** [comment]
I believe `uuid` can be dropped.

Only `v4` is used, and can be replaced by `randomUUID` from `node:crypto` : https://nodejs.org/docs/latest-v18.x/api/crypto.html#cryptorandomuuidoptions

**Comment by w666** [comment]
Removed requests and replaced uuid with built-in crypto.randomUUID(). 

Also run a smoke test against latest node 14, all worked, so we still support node 14+.

**Comment by w666** [comment]
I've just published new release 1.0.4 with some improvements. 
Planning to include this PR in the next release and increment minor version (1.1.0) as it contains some pretty major changes.

I am still getting feedback about these changes, feel free to add comments. Thanks.

**Pull request merged**
