### PR TITLE
Fix Array serialization

### PR DESCRIPTION
**Pull request by theanimal666**
This PR is not to be merged (test are failing!) it's just to demonstrate the issue originally described in https://github.com/vpulim/node-soap/issues/748, 

original issue text below:

Hallo,

First of all thanks for this great library.

I'm working on an API and having troubles because of the way arrays get serialized into the request body.

My input object looks like:

```
{
options:
  [{
   option: {
      optionName: 'optname1',
      optionValue: 'value1'
    }
   },{
    option: {
      optionName: 'optname2',
      optionValue: 'value2'
    }
 }]
}
```
it gets serialized to:
```
<options>
   <option>
       <optionName>optname1</optionName>
       <optionValue>value1</optionValue>
   </option>
</options>
<options>
   <option>
       <optionName>optname2</optionName>
       <optionValue>value2</optionValue>
   </option>
</options>
```

while the server expects it to be formatted as:
```
<options>
   <option>
       <optionName>optname1</optionName>
       <optionValue>value1</optionValue>
   </option>
   <option>
       <optionName>optname2</optionName>
       <optionValue>value2</optionValue>
   </option>
</options>
```

I found the responsible code (llib/wsdl.js l: 1528..) and implemented a fix in my local fork but this causes several tests to fail.
I'm not really deep into this SOAP/XML stuff an therefore i'm not sure if that is a issue of the library or just bug in the servers SOAP server implementation.

thanks in advance for you help,
kind regards

### CODE REVIEW

**Comment by theanimal666** [comment]
Hi, 

As written im the PR i DID NOT WANT this to be merged - I KNOW that there are tests missing. 
My Point was that i wanted to know if this is really a bug in the library - or the expected bahaviour...

kind regards

**Comment by jsdevel** [comment]
> i wanted to know if this is really a bug in the library - or the expected bahaviour

I think if it doesn't follow the standards then its a bug.

**Comment by theanimal666** [comment]
i fixed the issue in a fork as i need it for a project. As i'm not into SOAP internals I HAVE NO IDEA what the standard here is... (already wrote that in the initial PR) 
So before i get my hand dirty implementing tests for the fix i simply wanted to know if it's worth the work as i'm not into the code and it would require quite some time for me to provide tests.

kind regards

**Comment by LeandroFavero** [comment]
I have the same problem. Delphi use this "standard" and a TOTVS (https://www.totvs.com/) too.

My idea is has an option in module, to setup each kind of serialization use.

**Pull request closed without merging**
