### PR TITLE
Return error in event of an empty response body

### PR DESCRIPTION
**Pull request by david-martin**
If the SOAP service you're calling is sometimes flaky,or perhaps theres an proxy problem that causes intermittent empty response bodies, results in:
TypeError: Parse buffer must be String or Buffer.

This change will allow the developer to handle them more gracefully.

### CODE REVIEW

**Comment by herom** [comment]
I'm closing this PR as there was no activity for nearly a year now...

**Comment by david-martin** [comment]
@herom this completely fell off my radar. Apologies for not following up

**Comment by herom** [comment]
No problem @david-martin - I was just roaming the open Pull Requests and decided to close the ones which obviously were orphaned.

If you can/want to follow up on this PR please feel free to reopen it and follow our [Guidelines on Submitting a Pull Request](https://github.com/vpulim/node-soap/blob/master/CONTRIBUTING.md#submitting-a-pull-request), we'd appreciate it a lot :smiley_cat:

**Comment by alpertandogan** [comment]
nodejs server works well in local but behind proxy get an error 

-------------apache2 config file
    Header set Access-Control-Allow-Origin "*"

    
    SSLProxyEngine on
    ProxyRequests On
   
	ProxyPreserveHost On
    ProxyBadHeader Ignore 
    ProxyVia Full


	# RewriteEngine On
	# #nj api server                 ***kdx_main.js 
	# RewriteCond %{REQUEST_URI}  ^/kss            [NC]
	# RewriteCond %{QUERY_STRING} transport=websocket    [NC]
	# RewriteRule /(.*)           ws://127.0.0.1:8001/$1 [P,L]	
	ProxyPass        "/kss" "http://127.0.0.1:8001"
	ProxyPassReverse "/kss" "http://127.0.0.1:8001"

    
    ProxyPassReverseCookiePath / /kss
    LogLevel debug
    ProxyTimeout 600

    # Directory settings for /var/www/soap
    <Directory "/var/www/soap">
        Options Indexes FollowSymLinks
        AllowOverride None
        Require all granted
    </Directory>
    
    # Directory access
    <Location />
        Require all granted
    </Location>

-------------apache2 config file


SOAP client successfully created.
{
  BKMVendorFieldServiceWS: {
    BKMVendorFieldServiceWSSoap: { seriNoDogrulama: [Object], isEmriGiris: [Object] },
    BKMVendorFieldServiceWSSoap12: { seriNoDogrulama: [Object], isEmriGiris: [Object] }
  }
}
No response body received or response is incomplete: { Body: null }

**Comment by w666** [comment]
Hi @alpertandogan,

If you have a fix for that feel free to raise a PR. Thanks.

**Pull request closed without merging**
