### PR TITLE
[Proposal] Generic XML string transformation before request

### PR DESCRIPTION
**Pull request by endorama**
Hello! First of all thanks for this library.

I had a problem using it due to a "strange" constrain in the SOAP API I have to use. Strange because I wasn't able to find information about a `ent` namespace in SOAP requests...
I'm a SOAP noob, so please forgive incorrectness or silly errors :)

For some reason the API instead of using `tns` ( I guess this is a xml namespace ) uses `ent`. This is in conflict with the generated request XML. I tried to dig in `node-soap` source code to find a way to change this but wasn't able to find one. My solution is a generic callback function to edit the XML before is sent ( simple RegExp search&replace ). It seems that `xmlns:tns` is taken from the `WSDL` definition ( so it is actually "expected" but the request returns an error without `ent` ).

I thought that maybe this could be useful, so here is this PR. Is more a proposal than a feature request.  
If there is already a way to perform this that I missed, please let me know.

Thank you.

PS: I wasn't able to create tests for this feature, but if you like the proposal and explain me how to create them, I will.

### CODE REVIEW

**Comment by herom** [comment]
Hello @endorama - thanks a lot for your time & effort :+1: 

Is the purpose of your PR to ensure that the `ent` namespace is taken into account and served as well or to be ignored like the `tns` namespace? From your tests, it's not clear how the issue of the (missing?) `ent` namespace is related to it as it's only testing the presence of the `options` object on the client instance. I'll rather go for tests which ensure that your `xmlTransform` function on the `options` object is executed, etc.

Also, if we introduce this feature it would be necessary to mention it in our README. It would be awesome if you could provide another PR for adding some documentation on the `options` object and the newly introduced `xmlTransform` "hook".

In order to get your PR merged, please take a look at our [Guidelines on Submitting a Pull Request](https://github.com/vpulim/node-soap/blob/master/CONTRIBUTING.md#submitting-a-pull-request) and go through the steps provided over there. Namely, the following steps are necessary in order to merge your PR:

- Provide accompanying tests (it would be awesome if you could also provide tests for the `xmlTransform` "hook" and a "Request Response Sample~ which shows what you're trying to achieve (it would be best - I guess - if you show it with your `ent` namespace example)
- Rebase/squash your commits into a single one and rebase them on latest master so it could be merged automatically through GitHub (for more information see the Guidelines)

Thanks a lot in advance :smile_cat:

**Comment by endorama** [comment]
Thanks for your feedback! As I wasn't sure about this PR, I didn't squashed commits to better clarify code edits, I'll do it when ready for merging :)

To clarify my proposal: I have this code for a SOAP request
```javascript
var url = 'https://example.com/endpoint?wsdl';
var args = {
  token: {
    tokenId: '...',
    locale: 'IT',
    authenticationUser: {
      username: '',
      password: ''
    }
  },
  .
  .
  .
};

soap.createClient(url, function(err, client) {
  if (err) { callback(err, null); }
  client.getChargingUnitsList(args, function(err, result) {
    if (err) { callback(err, null); }
    else { callback(null, result); }
  });
});
```

The XML sent for this request is:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:tns="http://example.com/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <soap:Body>
    <getChargingUnitsList>
      <token>
        <tokenId>...</tokenId>
        <locale>IT</locale>
        <authenticationUser>
          <username />
          <password />
        </authenticationUser>
      </token>
      .
      .
      .
    </getChargingUnitsList>
  </soap:Body>
</soap:Envelope>
```

The problem with this XML is that the endpoint is expecting this:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ent="http://example.com/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <soap:Body>
    <ent:getChargingUnitsList>
      <token>
        <tokenId>...</tokenId>
        <locale>IT</locale>
        <authenticationUser>
          <username />
          <password />
        </authenticationUser>
      </token>
      .
      .
      .
    </ent:getChargingUnitsList>
  </soap:Body>
</soap:Envelope>
```
Please notice the `ent` in the second line and before `getChargingUnitsList`. The xmlTranform that I defined to achieve this is:
```javascript
function _xmlTransformationCallback (xml) {
  xml = xml
          .replace(/xmlns:tns/, 'xmlns:ent')
          .replace(/getChargingUnitsList/g, 'ent:getChargingUnitsList');
  return xml;
}
```

The code is really simple, was just a quick hack to achieve my needs. I thought that could be a useful addition, and I know it still needs some work ( for example if you do not return something from the callback the xml var will became `undefined` which is obviously something you would like to check ).

I'll try to add some checks and the missing tests! :) Thank you

**Comment by endorama** [comment]
I added Unit Tests for the xmlTransform feature, but unfortunately wasn't able to add a "Request Response Sample"; I didn't understand how to add my test case.

I have also updated the Readme with the relevant informations.

**Comment by jsdevel** [comment]
@endorama you should be able to change the namespace now by prefixing like `ent:elementName`.  Also, [object-mapper](https://www.npmjs.com/package/object-mapper) is a really nice module for transforming soap requests.

**Comment by jsdevel** [comment]
Closing for lack of activity.

**Comment by endorama** [comment]
I can rebase and squash it if you are still interested in the PR :)

**Comment by jsdevel** [comment]
Is this still needed?

**Comment by endorama** [comment]
You're right, the same thing can be achieved using the new prefix overrides! Sorry

**Comment by jsdevel** [comment]
no worries!  Thanks for your efforts!

**Pull request closed without merging**
