### PR TITLE
Fix missing parameter in example

### PR DESCRIPTION
**Pull request by dj95**
The example in the README does not include a required parameter. If this parameter is omitted, the client will always be `undefined`.

### CODE REVIEW

**Comment by dj95** [comment]
Since you do not seem to care about pull requests I'll close this one one...

**Comment by jsdevel** [comment]
@dj95 so harsh!  please re-open.  sorry, i usually go through the open PRs every month or so.

**Comment by dj95** [comment]
Since there was progress on other issues I thought that you might not care. Sorry for my impatience!

**Comment by dj95** [comment]
Thank you for reopening and merging the PR :)

**Pull request merged**
