### PR TITLE
Fix for custom namespace for arrays.

### PR DESCRIPTION
**Pull request by kamilwojdylo**
I will add comments at the weekend maybe earlier.

### CODE REVIEW

**Comment by jsdevel** [comment]
@kamilwojdylo looks like the build failed.  Also, can you add  atest?

**Comment by herom** [comment]
ping @kamilwojdylo: do you still have some sparetime to adjust this PR or is this abandoned?

**Comment by joviol** [comment]
Was wondering when this fix will be in production. I am having an issue with arrays:
**"q3:somefield": [...]**

becomes:
**<semefield>...</somefield>**
in the envelope

can't proceed any further in my project without this fix

**Comment by herom** [comment]
as you can see @joviol, this PR was unfortunately abandoned by its initiator and so - unless somebody will step in or the initiator changes his/her mind - this PR will be left unfinished and probably closed in the near future.

if you have some spare time and are willing to take over this PR we'd happily merge it in :+1:

**Comment by jsdevel** [comment]
closing due to inactivity

**Pull request closed without merging**
