### PR TITLE
change content-type-parser to whatwg-mimetype

### PR DESCRIPTION
**Pull request by lagden**
Regular Expression Denial of Service (ReDoS)
https://snyk.io/test/npm/content-type-parser/1.0.2

### CODE REVIEW

**Comment by jsdevel** [comment]
@lagden sorry for the late reply, can you resolve the conflicts?

**Comment by lagden** [comment]
done

**Comment by jsdevel** [comment]
@lagden please ensure the build passes

**Comment by nwall123** [comment]
Hi guys. Just wondering is there a plan to fix this and would you have a date in mind? Thanks

**Comment by jsdevel** [comment]
waiting on the build to be fixed.  @lagden can you fix it?

**Comment by khadeamolm** [comment]
@jsdevel - Not able to fix the build issue with these code changes. Please assist us to fix this issue. Our project is impacted due to this issue.

**Comment by jsdevel** [comment]
@khadeamolm you'll have to dig into it and fix it.

**Comment by smokhov** [comment]
@jsdevel -- please close this, since you merged #1177 that superseded it. Also #1164 can be addressed with the form and closed.

**Pull request closed without merging**
