### PR TITLE
Fixed problem with converting objects inside $value

### PR DESCRIPTION
**Pull request by jadbaz**
This is my input:
```
{
    "simpleParam1": "arp",
    "simpleParam2": "xyz",
    "arrayParam": {
        "propArray": [
            {
                "name": "prop1",
                "value": "123"
            },
            {
                "name": "prop2",
                "value": "789"
            }
        ]
    }
}
```

If I convert it as is, it works just fine. However, I want to add an attribute: ```xmlns=""```
So my input looks like this:

```
{
    "exampleAction": {
        "simpleParam1": {
            "$value": "abc",
            "attributes": {
                "xmlns": ""
            }
        },
        "simpleParam2": {
            "$value": "xyz",
            "attributes": {
                "xmlns": ""
            }
        },
        "arrayParam": {
            "$value": {
                "propArray": [
                    {
                        "name": "prop1",
                        "value": "123"
                    },
                    {
                        "name": "prop2",
                        "value": "789"
                    }
                ]
            },
            "attributes": {
                "xmlns": ""
            }
        }
    }
}
```

Before: would convert to:
```
<exampleAction xmlns="http://ws.example.net/">
	<simpleParam1 xmlns="">abc</simpleParam1>
	<simpleParam2 xmlns="">xyz</simpleParam2>
	<arrayParam xmlns="">
		[object Object]
	</arrayParam>
</exampleAction>
```

Fixed: would convert to (as expected)
```
<exampleAction xmlns="http://ws.example.net/">
	<simpleParam1 xmlns="">abc</simpleParam1>
	<simpleParam2 xmlns="">xyz</simpleParam2>
	<arrayParam xmlns="">
		<propArray>
			<name>prop1</name>
			<value>123</value>
		</propArray>
		<propArray>
			<name>prop2</name>
			<value>789</value>
		</propArray>
	</arrayParam>
</exampleAction>
```

### CODE REVIEW

**Comment by herom** [comment]
Thanks a lot for your time and effort @jadbaz - we appreciate it a lot :+1: 

In order to get your PR merged, please follow our [Guidelines on Submitting a Pull Request[(https://github.com/vpulim/node-soap/blob/master/CONTRIBUTING.md#submitting-a-pull-request).

**Comment by jadbaz** [comment]
Sorry, there was a slight error, here is the updated block:
```
      //Its the value of an item.
      if (name === self.options.valueKey) {
        //If the value is an array or an object, go through it.
        if (typeof obj[name] === 'object')
        {
          return self.objectToXML(obj[name], name, namespace, xmlns, false, null, parameterTypeObject, ancXmlns);
        }
        //Otherwise, return it as is.
        else
        {
          return xmlEscape(obj[name]);
        }
      }
```

To be honest, I'm fairly new to git and I'm not exactly sure how or where I should include tests.
I also have yet to learn about rebasing, etc...
In any case, this is what I have at the moment. You can either merge it now yourself or wait for me to update it.
Thank you

**Comment by herom** [comment]
No problem @jadbaz - we all once started with git and github alltogether :smile: 

The best thing would be to add a test in  `test/request-response-samples` as your introductory message already describes what's your input and the expected output you'll half way there :+1: 

For squashing commits (which is basically a tool to "melt" several commits into each other and change/rewrite the commit message along these lines) you can find links to the pretty good GitHub Help pages in our `CONTRIBUTING.md` file.

**Comment by herom** [comment]
@VilleMiekkoja or why do you request a "reopen"?

**Comment by michaelarnauts** [comment]
It seems that this is still an issue, or is there another way to do this?

**Comment by jsdevel** [comment]
@michaek we never got tests.  feel free to plagiarize this PR and add some tests.

**Comment by aditya-skeps** [comment]
This bug doesn't allow me to create complex xml structure where there is a need for both child elements and attributes. Is there a way this can be handled?

**Comment by aditya-skeps** [comment]
Found a workthrough using postProcess in method call
`
options.postProcess = function (_xml) {
        return _xml.replace("<api:Item>", "<api:Item key=\"newRequest\">")
}
`

**Comment by jsdevel** [comment]
@aditya-skeps can you open a PR and add this to the README?

**Pull request closed without merging**
