### PR TITLE
add options for username and password in WSSecurityCert

### PR DESCRIPTION
**Pull request by jakobrun**

### CODE REVIEW

**Comment by jsdevel** [comment]
@jakobrun i'm still seeing conflicts in the gh ui.

**Comment by jakobrun** [comment]
image
@jsdevel this is what I see

**Comment by jsdevel** [comment]
Ahh, i had the rebase and merge option enabled (what i usually do on gh).  Looks good to me.  @herom thoughts?

**Comment by juandavidrobles** [comment]
Hey @jakobrun  I must to say that your are so awesome. I tried your code and it worked perfectly. I was driving me crazy while trying to consume a WS with WS-Security and WS-Security cert (signed) unsuccessfully.

**Comment by jakobrun** [comment]
@juandavidrobles thanks :)

**Comment by jsdevel** [comment]
@jakobrun sorry to bring this up _yet_ again, but there are more conflicts.  can you resolve them?  i'm working through the PRs from the bottom up and will not address any other issues until this one is merged

**Comment by mancioshell** [comment]
is it this pr merged?

**Pull request closed without merging**
