### PR TITLE
Children may be empty resulting in a NPE

### PR DESCRIPTION
**Pull request by tobias-neubert**
I think the title says it all :-)

Tobi

### CODE REVIEW

**Comment by jsdevel** [comment]
Can you add to `test/request-response-samples`?  We'll need a way to re-create this.

**Comment by tobias-neubert** [comment]
Ok, added a test. Hope it helps.

**Comment by jsdevel** [comment]
It does!  Thank you!  Can you squash down to 1 commit?

**Comment by tobias-neubert** [comment]
What do I have to do to repeat the tests? It seems something out of my scope went wrong.

**Comment by jsdevel** [comment]
@tobias-neubert there should be a rerun build button in travis, but it looks like coveralls is failing.See this issue: https://github.com/lemurheavy/coveralls-public/issues/713

**Comment by jsdevel** [comment]
Thanks for the contribution @tobias-neubert !

**Pull request merged**
